# This file is chronological: blocks nearer the top will always appear before
# blocks nearer the bottom when placed into a course's timeline

# Block kind
# 0. In class
# 1. Assignment
# 2. Milestone
# 3. Custom
# 4. Training

# Week weight
# - The app will attempt to evenly distribute weights across the course timeline
# - Higher weights will be more likely to stand on their own
# - Weights may be any positive number but 1-10 is recommended

essentials:
  - # generic preparation material
    weight: 1
    blocks:
      -
        title: Introduction to the Wikipedia project
        kind: 0
        content: |
          <p>
            Welcome to your Wikipedia project's course timeline. This page will
            guide you through the Wikipedia project for your course. Be sure to
            check with your instructor to see if there are other pages you should
            be following as well.
          </p>
          <p>
            Your course has also been assigned a Wikipedia Content Expert. Check
            your Talk page for notes from them. You can also reach them through
            the "<strong>Get Help</strong>" button on this page.
          </p>
          <p>
            To get started, please review the following handouts:
          </p>
          <ul>
            <li><a href="http://wikiedu.org/editingwikipedia">Editing Wikipedia</a> pages 1–5</li>
            <li><a href="http://wikiedu.org/evaluatingwikipedia">Evaluating Wikipedia</a></li>
          </ul>

      -
        title: Get started on Wikipedia
        kind: 1
        graded: true
        points: 5
        training_module_ids: [1, 2] # Wikipedia essentials, Editing basics
        content: |
          <ul>
            <li>
              Create an account and join this course page, using the  enrollment
              link your instructor sent you. (To avoid hitting Wikipedia's account
              creation limits, this is best done outside of class. Only 6 new accounts
              may be created per day from the same IP address.)
            </li>
            <li>
              It's time to dive into Wikipedia. Below, you'll find the first set
              of online trainings you'll need to take. New modules will appear
              on this timeline as you get to new milestones. Be sure to check
              back and complete them! Incomplete trainings will be reflected in
              your grade.
            </li>
            <li>
              When you finish the trainings, practice by introducing yourself to
              a classmate on that classmate’s Talk page.
            </li>
          </ul>

evaluate_an_article:
  - # EVALUATE
    weight: 1
    blocks:
      -
        title: Evaluate a Wikipedia article
        kind: 1
        graded: true
        points: 10
        training_module_ids: [7] # Evaluate an article
        content: |
          <p>
            In this assignment, you'll evaluate a Wikipedia article related to
            the course. The goal of this assignment is to get you thinking about
            what a "good" Wikipedia article might look like and to learn how to
            evaluate an article on Wikipedia for quality.
          </p>
          <p>
            When you're ready, search for an article on <a href="https://en.wikipedia.org/">Wikipedia</a>
            using the "Search Wikipedia" toolbar on the Wikipedia home page. The
            topic you choose should be related to your course or something you're
            personally interested in. Then, read through it. After you've read
            through the article once, create a section in <a href="https://en.wikipedia.org/wiki/Special:MyPage/sandbox">your Sandbox</a>
            titled "Article evaluation" where you'll leave notes about your
            observations and learnings.
          </p>
          <p>
            When you have your section ready, review the article again. As you
            read, consider the following questions and include your notes in
            your Sandbox (but don't feel limited to these):
          </p>
          <ul>
            <li>How does the way Wikipedia discusses this topic differ from the way we've talked about it in class?</li>
            <li>Is everything in the article relevant to the article topic? Is there anything that distracted you?</li>
            <li>Is the article neutral? Are there any claims that appear heavily biased toward a particular position?</li>
            <li>Are there viewpoints that are overrepresented, or underrepresented?</li>
            <li>
              Go to the References section and check a few citations. Do the
              links work? How many of the sources provided are from the last
              year? The last five years?
            </li>
            <li>
              Is each fact referenced with an appropriate, reliable reference?
              Where does the information come from? Are these neutral sources?
              If biased, is that bias noted?
            </li>
            <li>
               Check out the Talk page of the article. What kinds of conversations,
               if any, are going on behind the scenes about how to represent this topic?
            </li>
            <li>
              Also, on the Talk page, check to see how the article is rated
              (if it's rated at all). Is it a part of any WikiProjects?
            </li>
          </ul>
          <h4>
            Additional resources & assigned readings
          </h4>
          <ul>
            <li><a href="https://wikiedu.org/evaluatingwikipedia">Evaluating Wikipedia</a></li>
          </ul>
          <h4>
            Tips
          </h4>
          <ul>
            <li>
              When editing most Wikipedia pages (except Talk page), you can
              switch between 'Visual editing' and 'Source editing'. To switch,
              click the pencil icon at the top right of the editing window.
            </li>
          </ul>

add_to_article:
  - # ADD TO AN ARTICLE
    weight: 1
    blocks:
      -
        title: Add to an article
        kind: 1
        training_module_ids: [8] # Sources and Citations
        graded: true
        points: 10
        content: |
          <p>
            In this assignment, you'll make a <em>live</em> edit on Wikipedia. This
            means you're being asked to add new content to an article. This new
            content should include one or two new sentences, backed up with a
            related citation.
          </p>
          <p>When you're ready, choose one of these two options:</p>
          <ul>
            <li>
              <strong>Option 1:</strong> Search or browse for an article on Wikipedia.
              The topic you select should be related to your course or something
              you're personally interested in and read through it. Find one small
              thing that you think is missing, then search for a source online
              that can help you fill that need. When you're ready, <em>Edit</em>
              the page and draft up your contribution. Then, use the <em>Cite</em>
              tool to add your citation. When you're done, save your changes!
            </li>
            <li>
              <strong>Option 2:</strong> The <a href="https://tools.wmflabs.org/citationhunt/en">Citation Hunt</a>
              shows unreferenced statements from articles. First, evaluate whether
              the statement in question is true! An uncited statement could just
              be lacking a reference or it could be inaccurate or misleading.
              Next, find a citation to help you complete the request. Reliable
              sources on the subject will help you choose whether to add it or
              correct the statement. Once you've found what you want to change,
              <em>Edit</em> the page and draft up your contribution. Then, use
              the <em>Cite</em> tool to add your citation. When you're done,
              save your changes!
            </li>
          </ul>
          <h4>
            Tips
          </h4>
          <ul>
            <li>
              For adding citations and new text, we recommend using <em>Visual editing</em>.
              You can switch from (or to) <em>Source editing</em> by clicking the pencil icon,
              once you've entered edit mode.
            </li>
            <li>
              Don't forget to leave an edit summary of what you contributed! Did
              you add a new reference or external link to the article? Awesome!
              Let the other Wikipedian's working on the article know. Whenever
              you make an edit on Wikipedia you should always save an edit summary.
            </li>
            <li>Make sure you are logged in or else the Dashboard can't track your work!</li>
          </ul>

illustrate:
  - # ILLUSTRATE
    weight: 1
    blocks:
      -
        title: Illustrate an article
        kind: 1
        graded: true
        points: 10
        training_module_ids: [6] # Images and multimedia
        content: |
          <p>You'll want to find or create an appropriate photo, illustration, or piece of video/audio to add to an article.</p>
          <ul>
            <li>
              Before you start, review the <a href="http://wikiedu.org/illustratingwikipedia">Illustrating Wikipedia</a> handbook,
              or see <a href="http://wikiedu.org/editingwikipedia">Editing Wikipedia</a> pages 10–11.
            </li>
            <li>When you've reviewed those pages, take the training linked below.</li>
            <li>
              When you're ready to start finding images, remember: <strong>Never</strong>
              grab images you find through an image search, or those found on
              Instagram, Tumblr, Reddit, Imgur, or even so-called "Free image" or
              "free stock photo" websites. Instead, you'll want to find images
              with clear proof that the creator has given permission to use their
              work. Many of these images can be found on
              <a href="http://search.creativecommons.org/">search.creativecommons.org</a>.
            </li>
            <li>
               Don't just upload an image to Wikipedia. Instead, upload it to
               Wikipedia's sister site for images, Wikimedia Commons. For
               instructions, read through the <a href="http://wikiedu.org/illustratingwikipedia">Illustrating Wikipedia</a> handbook.
            </li>
          </ul>

copyedit:
  - # COPYEDIT
    weight: 1
    blocks:
      -
        title: Copyedit an article
        kind: 1
        graded: true
        points: 10
        content: |
          <p>
            In this assignment, you'll make a <em>live</em> edit on Wikipedia. This
            means you're being asked to add new content to an article. This new
            content should include only copyedits, such as grammatical changes.
          </p>
          <p>
            Search or browse for an article on Wikipedia. The topic you choose
            can be the same one you evaluated, a new one related to your course,
            or anything else. Once you have your article selected, read through
            it, thinking about ways to improve the language, such as fixing
            grammatical mistakes. (If you can't find anything to improve, browse
            until you find an article that needs more help.) Then, click <em>Edit</em>
            to make the appropriate changes, and save it when you're done. You
            don’t need to contribute new information to the article for this assignment.
          </p>
          <h4>
            Tips
          </h4>
          <ul>
            <li>
              For copyedits and article contributions, we recommend using <em>Visual editing</em>.
              You can switch from (or to) <em>Source editing</em> by clicking the pencil icon,
              once you've entered edit mode.
            </li>
            <li>
              Don't forget to leave an edit summary of what you contributed! Did
              you fix a typo? Awesome! Let the other Wikipedian's working on the
              article know. Whenever you make an edit on Wikipedia you should always
              save an edit summary.
            </li>
          </ul>
